# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8977b75a3b66387c0bf9c3cce601020c598d601bb630d68c5f01957391f12fd1ae874a7a08a717cd549b3357e227d23addea4da9648f699109580411a81d9209

test:
  secret_key_base: 4bef4d65f3010e69b3a7647c7bb8e813cd59636db155fe7a0b6ea6923ce3860b561295147ca68b20f9d65f126655bbc7a75e69946b71a82851ffedcb6d402d83

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
